#DEV environment

app.message="THis is property file for the ${spring.application.name} to PROD ENV"

spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=<MYSQL_URL>
spring.datasource.username=<USERNAME>
spring.datasource.password=<PASSWORD>



